apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  # namespace: cert-manager
spec:
  acme:
    # Configure your email here...
    # ---
    email: mydomain@mail.com # TODO: Change This

    # Configure your server here...
    # ---
    # Letsencrypt Production
    server: https://acme-v02.api.letsencrypt.org/directory
    # - or -
    # Letsencrypt Staging
    # server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    # Configure DNS or HTTP Challenge here...
    # ---
    # DNS Challenge:
    - dns01:
        # Configure your DNS Provider here...
        # ---
        cloudflare:
          email: mydomain@mail.com  # TODO: Change This
        # API Key:
        #   apiKeySecretRef:
        #     name: cloudflare-api-key-secret
        #     key: api-key
        # - or -
        # API Token:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token        
      # (Optional) Add DNS selectors
      # ---
      # selector:
      #   dnsNames:
      #   - 'your-domain'
      #   - '*.your-domain'

    # HTTP Challenge:
    # - http01:
    #    ingress:
    #      class: traefik
