apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert
spec:
  secretName: ssl-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: # TODO: Change This
  - '*.glimmova.com'
  - 'glimmova.com'
