image:
  registry: docker.io
  repository: drone/kubernetes-secrets
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

rbac:
  enabled: true
  secretNamespace: drone

env:
  ## REQUIRED: Shared secret value for comms between the Kubernetes runner and this secrets plugin.
  ## Must match the value set in the runner's env.DRONE_SECRET_PLUGIN_TOKEN.
  ## Ref: https://kube-runner.docs.drone.io/installation/reference/drone-secret-plugin-token/
  ## This is commented out in order to leave you the ability to set the
  ## key via a separately provisioned secret (see existingSecretName above).
  SECRET_KEY: de24501127ad7944332d04688638fdd8
  KUBERNETES_NAMESPACE: drone

