apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  # namespace: ai
data:
  # value from this code: cat ~/.docker/config.json | base64 -w0  # TODO: Change This
  .dockerconfigjson: # TODO: Change This
type: kubernetes.io/dockerconfigjson
