---
# tasks file for configure-network-rules

- name: Creating a configuration file for containerd
  become: true
  file:
    path: "/etc/modules-load.d/containerd.conf"
    state: "touch"

- name: Setting up pre-requisites for containerd
  become: true
  blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
          overlay
          br_netfilter

- name: Applying the kernel modules...
  become: true
  shell: |
        modprobe overlay
        modprobe br_netfilter

- name: Creating kubernetes config file for host network...
  become: true
  shell:
    cmd: |
        cat <<__EOF__ >  /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables=1
        net.bridge.bridge-nf-call-iptables=1
        __EOF__
  args:
    chdir: /etc/sysctl.d
    creates: k8s.conf

- name: Applying sysctl file config...
  become: true
  shell: sysctl --system

- name: Applying newly created kubernetes config file...
  become: true
  shell: sysctl -p /etc/sysctl.d/k8s.conf

- name: Applying containerd settings...
  become: true
  shell: |
        mkdir -p /etc/containerd
        containerd config default | sudo tee /etc/containerd/config.toml
        sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
        sudo systemctl enable containerd
        sudo systemctl restart containerd

- name: Deploying docker iptables rule...
  become: true
  shell: iptables -P FORWARD ACCEPT

- name: Disabling UFW...
  become: true
  ufw:
    state: disabled
