version: '3.8'
services :
  db:
    # image: postgres:latest
    image: postgres
    container_name: pg_container
    restart: unless-stopped
    ports:
      - "${PGPORT:-5432}:${PGPORT:-5432}"
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDB:-postgres}
      # PGDATA: /var/lib/postgresql/data/ # <-- Check this out
    volumes: 
      # - db-data:/var/lib/postgresql/data/:rw  # <-- this is for named volumes
      - ${POSTGRES_DATA-./postgres_data}:/var/lib/postgresql/data/:rw # <-- this is for bind volume
      # - ./dbscripts:/docker-entrypoint-initdb.d

  # # adminer tool
  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: unless-stopped
  #   depends_on: 
  #     - db
  #   ports:
  #     - 8080:8080
  #   # network_mode: host

  # pgadmin tool

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=metin_karakus@yahoo.com
      - PGADMIN_DEFAULT_PASSWORD=passwd
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "${PGADMIN_PORT:-5050}:${PGADMIN_PORT:-5050}"
    depends_on:
      - db
    # network_mode: host

# # if you want to use named volue uncomment this
# volumes:
#   db-data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${PWD}/postgres_data #NOTE needs full path (~ doesn't work)
