version: '3.8'
services :
  db:
    image: postgres
    container_name: pg_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes: 
      - db-data:/var/lib/postgresql/data
      # - ./dbscripts:/docker-entrypoint-initdb.d

  # # adminer tool 
  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: unless-stopped
  #   depends_on: 
  #     - db
  #   ports:
  #     - 8080:8080
  #   # network_mode: host

  # pgadmin tool 
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=youremail@whatever.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    depends_on: 
      - db
    # network_mode: host

volumes:
  db-data: